[package]
name = "amp-client"
description = "The Amphitheatre API client for Rust"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://amphitheatre.app"
repository = "https://github.com/amphitheatre-app/amp-client-rust"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amp-common = { git = "https://github.com/amphitheatre-app/common" }
ureq = { version = "2.5.0", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
thiserror = "1.0"

[dev-dependencies]
mockito = "0.31"
assert_matches = "1.5"